title: Amy Elliott
subtitle: Gameplay Programmer
description: >- # this means to ignore newlines until "baseurl:"
  amy elliott

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blogs
      url: /blog
    - text: Game Library
      url: /game-library
    - text: Contact
      url : /contact
    - text: CV
      url : /cv


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Amy Elliott
author_bio: My name is Amy, and I'm a gameplay programmer from the UK.<br />
            I've published my first game on the Google Playstore when I was 17, and I'm currently a student on a gap-year at the University of Portsmouth studying Computer Games Technology BSc (Hons), as well as doing Commission Artwork and working at Jagex.<br /> 
            I've recently graduated from Northbrook Metropolitan College with a Disctinction grade, studying Games Development.<br />
            I love learning new skills and taking on challenges, I achieve this by working hard and doing lots of self-directed study in hopes to have T shaped knowledge.
author_email: "amy.elliott2002@yahoo.co.uk"
author_location: United Kingdom
author_website_url: "https://amy-portfolio.com"
typewrite-text: I'm a Gameplay Programmer!

# Experiences
author_work_experiences:
            - company_name: Jagex
              company_logo: jagex.png
              company_url: https://www.jagex.com/en-GB/
              work_duration: May 2021 - Aug 2021
              designation: Game Engineer Intern
              description: Worked on Programming in a Triple-A Industry environment.
              visibility: true  
            - company_name: Submarine Simulator for The Royal Navy
              company_logo: rn.png
              company_url: https://www.royalnavy.mod.uk/careers/roles-and-specialisations/services/submarine-service
              work_duration: Dec 2020 - Apr 2021
              designation: Lead Programmer
              description: Worked in collaboration with The Royal Navy to produce a submarine simulator for recruitment events
              visibility: true
            - company_name: Commission Work
              company_logo: commission.png
              company_url: https://art.amy-portfolio.com
              work_duration: Aug 2020 - Present
              designation:  Freelance Artist
              description: Worked with clients to produce character designs and illustrative pieces.
              visibility: true
            - company_name: CeX Ltd.
              company_logo: cex.png
              company_url: https://uk.webuy.com/
              work_duration: Jun 2018 - May 2021
              designation: Retail Sales Assistant
              description: Served customers and helped them pick video games and electronics, I've also worked on testing and buying electronics.
              visibility: true

# Education
author_education_details:
              - college_logo: uop.png
                college_name: University of Portsmouth
                college_url: https://www.port.ac.uk/
                study_duration: 2020 - Present
                college_degree: Computer Games Technology
                description: Bachelor of Science
                visibility: true
              - college_logo: nbc.png
                college_name: Northbrook Metropolitan College
                college_url: https://www.gbmc.ac.uk/
                study_duration: 2018 - 2019
                college_degree: Games Development
                description: UAL Level 3 Diploma in Creative Media
                visibility: true


# Projects
author_project_details:
              - project_thumbnail: jagex.png
                project_title: Unannounced MMORPG
                project_description: Worked on the programming for an Unannounced Triple-A MMORPG.
                project_url: https://www.jagex.com/en-GB/
                blog_url: /wip
                date: In Progress
                engine: unrealengine.png
                language: cpp.png
                published: jagex.png
                role: Game Engineer Intern
                team: https://www.jagex.com/en-GB/
                dev: Jagex
                bp: <ul> 
                        <li>Working on Programming in a Triple-A Industry environment:</li-ph>
                            <ul>
                                <li>Working with different diciplines on the development team</li>
                                <li>Learning the most commonly used professional development tools</li>
                                <li>Experiencing how development teams prioritise and schedule their work</li>
                                <li>Contributing to various projects</li>
                            </ul>
                     </ul>
                visibility: true  
              - project_thumbnail: blocky.png
                project_title: Blocky Road
                project_description: A hyper-casual puzzle game, made in 15 hours.
                project_url: https://amy-elliott.itch.io/blockyroads
                blog_url: https://amy-portfolio.com/blocky-road
                date: 28th October, 2020
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Solo Project
                team: http://gamedev.amy-portfolio.com/blog/authors/amyelliott
                dev: Amy Elliott
                bp: <ul> 
                        <li>Programmed a two-way puzzle system:</li-ph>
                            <ul>
                                <li>Made sure there were different challenges on each side.</li>
                                <li>The puzzles can't be solved without the help from the opposite side.</li>
                            </ul>
                        <li>Inspired by mobile games like Crossy Road and Monument Valley</li>
                     </ul>
                visibility: true
              - project_thumbnail: subsim.png
                project_title: Planesman Trainer
                project_description: A submarine simulator game which was made for the Royal Navy's recruitment events
                project_url: https://www.royalnavy.mod.uk/careers/roles-and-specialisations/services/submarine-service
                blog_url: /wip
                date: 9th April, 2021
                engine: unity.png
                language: cs.png
                published: rn.png
                role: Lead Programmer
                team: http://gamedev.amy-portfolio.com/blog/authors/submariner#/
                dev: Team Submariner
                bp: <ul> 
                        <li>Programmed a majority of the main game systems</li-ph>
                            <ul>
                                <li>Worked on the periscope camera and the implementation</li>
                                <li>Helped my teammates learn how to use Unity and C# so no one was left hanging without a task</li>
                            </ul>
                        <li>Worked on finding assets and royalty-free materials to use for the environment</li>
                     </ul>
                visibility: true
              - project_thumbnail: tsh.png
                project_title: Team Swap Heroes
                project_description: A teamwork-based puzzle game made for Minijam 48.
                project_url: https://horsehead.itch.io/team-swap-heroes 
                blog_url: https://amy-portfolio.com/team-swap-heroes
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Programmer & Designer
                team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
                dev: Team Horsehead
                bp: <ul> 
                        <li>In charge of the main concepting and level designs:</li>
                            <ul>
                                <li>Worked on design, planning, implementing and testing a vast majority of the levels</li>
                                <li>Made the concept designs for the main character models, enemies and environment.</li>
                            </ul>
                        <li>Programmed the obstacle mechanics for each level and helped out with the player mechanics</li>
                     </ul>
                visibility: false
              - project_thumbnail: BeatCity.png
                project_title: Beat City
                project_description: A music based platformer game, developed by myself to experiment with music manipulation.
                project_url: https://amy-elliott.itch.io/beat-city
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                visibility: false
              - project_thumbnail: capsays.png
                project_title: Captain Says
                project_description: An educational action game, published to the Google Playstore.
                project_url: https://play.google.com/store/apps/details?id=com.AmyE.CaptainSays&hl=en_GB&gl=US
                blog_url: https://amy-portfolio.com/captain-says
                date: 31st August, 2019
                engine: unity.png
                language: cs.png
                published: gplaystore.png
                role: Programmer & Designer
                team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
                dev: Team Horsehead
                bp: <ul>                        
                        <li>Learnt how to publish games on the Google Playstore.</li>
                        <li>Programmed and designed the player movement for both webGL & mobile versions</li>
                        <li>Programmed the enemy system</li>
                        <li>Programmed the scoring and highscore system</li>
                        <li>Designed and implemented the UI</li>                        
                            <ul>
                                <li>Researched and implemented music feedback in the background and UI</li>
                            </ul>
                     </ul>
                visibility: false
              - project_thumbnail: pop.png
                project_title: Poppin Hoppin Unlockin
                project_description: A fantasy-platformer game, developed for a University Gamejam by a group which I lead.
                project_url: https://amy-elliott.itch.io/poppin-hoppin-unlockin
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                visibility: false

# Projects FOR HOMEPAGE
author_project_detailsHP:
              - project_thumbnail: jagex.png
                project_title: Unannounced MMORPG
                project_description: Worked on the programming for an Unannounced Triple-A MMORPG.
                project_url: https://www.jagex.com/en-GB/
                blog_url: /wip
                date: In Progress
                engine: unrealengine.png
                language: cpp.png
                published: jagex.png
                role: Game Engineer Intern
                team: https://www.jagex.com/en-GB/
                dev: Jagex
                bp: <ul> 
                        <li>Working on Programming in a Triple-A Industry environment:</li-ph>
                            <ul>
                                <li>Working with different diciplines on the development team</li>
                                <li>Learning the most commonly used professional development tools</li>
                                <li>Experiencing how development teams prioritise and schedule their work</li>
                                <li>Contributing to various projects</li>
                            </ul>
                     </ul>
                visibility: true    
              - project_thumbnail: blocky.png
                project_title: Blocky Road
                project_description: A hyper-casual puzzle game, made in 15 hours.
                project_url: https://amy-elliott.itch.io/blockyroads
                blog_url: https://amy-portfolio.com/blocky-road
                date: 28th October, 2020
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Solo Project
                team: http://gamedev.amy-portfolio.com/blog/authors/amyelliott
                dev: Amy Elliott
                bp: <ul> 
                        <li>Programmed a two-way puzzle system:</li-ph>
                            <ul>
                                <li>Made sure there were different challenges on each side.</li>
                                <li>The puzzles can't be solved without the help from the opposite side.</li>
                            </ul>
                        <li>Inspired by mobile games like Crossy Road and Monument Valley</li>
                     </ul>
                visibility: true
              - project_thumbnail: subsim.png
                project_title: Planesman Trainer
                project_description: A submarine simulator developed for the Royal Navy.
                project_url: https://www.royalnavy.mod.uk/careers/roles-and-specialisations/services/submarine-service
                blog_url: /wip
                date: 9th April, 2021
                engine: unity.png
                language: cs.png
                published: rn.png
                role: Lead Programmer
                team: http://gamedev.amy-portfolio.com/blog/authors/submariner#/
                dev: Team Submariner
                bp: <ul> 
                        <li>Programmed a majority of the main game systems</li-ph>
                            <ul>
                                <li>Worked on the periscope camera and the implementation</li>
                                <li>Helped my teammates learn how to use Unity and C# so no one was left hanging without a task</li>
                            </ul>
                        <li>Worked on finding assets and royalty-free materials to use</li>
                     </ul>
                visibility: true
              - project_thumbnail: tsh.png
                project_title: Team Swap Heroes
                project_description: A teamwork-based puzzle game made for Minijam 48.
                project_url: https://horsehead.itch.io/team-swap-heroes 
                blog_url: https://amy-portfolio.com/team-swap-heroes
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Programmer & Designer
                team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
                dev: Team Horsehead
                bp: <ul> 
                        <li>In charge of the main concepting and level designs:</li>
                            <ul>
                                <li>Worked on design, planning, implementing and testing a vast majority of the levels</li>
                                <li>Made the concept designs for the main character models, enemies and environment.</li>
                            </ul>
                        <li>Programmed the obstacle mechanics for each level and helped out with the player mechanics</li>
                     </ul>
                visibility: false
              - project_thumbnail: BeatCity.png
                project_title: Beat City
                project_description: A music based platformer game, developed by myself to experiment with music manipulation.
                project_url: https://amy-elliott.itch.io/beat-city
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                visibility: false
              - project_thumbnail: capsays.png
                project_title: Captain Says
                project_description: An educational action game on the Google Playstore.
                project_url: https://play.google.com/store/apps/details?id=com.AmyE.CaptainSays&hl=en_GB&gl=US
                blog_url: https://amy-portfolio.com/captain-says
                date: 31st August, 2019
                engine: unity.png
                language: cs.png
                published: gplaystore.png
                role: Programmer & Designer
                team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
                dev: Team Horsehead
                bp: <ul>                        
                        <li>Programmed and designed the player movement for both webGL & mobile versions</li>
                        <li>Programmed the enemy system, scoring and highscore system</li>
                        <li>Designed and implemented the UI</li>                        
                            <ul>
                                <li>Researched and implemented music feedback in the background and UI</li>
                            </ul>
                     </ul>
                visibility: true
              - project_thumbnail: pop.png
                project_title: Poppin Hoppin Unlockin
                project_description: A fantasy-platformer game, developed for a University Gamejam by a group which I lead.
                project_url: https://amy-elliott.itch.io/poppin-hoppin-unlockin
                date: 24th February, 2020
                engine: unity.png
                language: cs.png
                visibility: false


# social links
twitter_username: amyelliott_
github_username:  AmyE123
facebook_username: amy.elliott.773981
linkedin_username: amy-m-elliott
instagram_username: amy.m.elliott

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 6
per_page: 2
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
